// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearApiKey() {
    return $Call.ByID(2831717342);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ExportApiKeyToken() {
    return $Call.ByID(2247574838);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetApiKey() {
    return $Call.ByID(1661682315);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function LocalEndpoint() {
    return $Call.ByID(2575314742);
}

/**
 * @param {string} targetPath
 * @param {string} customCommand
 * @returns {$CancellablePromise<void>}
 */
export function OpenPath(targetPath, customCommand) {
    return $Call.ByID(447281479, targetPath, customCommand);
}

/**
 * @param {string} apiKey
 * @returns {$CancellablePromise<string>}
 */
export function SetApiKey(apiKey) {
    return $Call.ByID(3783879831, apiKey);
}
